name: Update Manifest

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  update:
    name: Update
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Scoop
        shell: pwsh
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $env:GITHUB_PATH

      - name: Update Noto Sans SC
        shell: pwsh
        run: scripts/Update-NotoSansSC.ps1

      - name: Commit Noto Sans SC Update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "noto-sans-sc: update to version ${{ env.NOTO_SANS_SC_VERSION }}"
          file_pattern: bucket/noto-sans-sc.json
